package net.ilexiconn.jurassicraft.client.model.entity;

import net.ilexiconn.jurassicraft.client.model.base.MowzieModelBase;
import net.ilexiconn.jurassicraft.common.entity.dinosaurs.EntityOviraptor;
import net.ilexiconn.jurassicraft.client.model.base.MowzieModelRenderer;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelOviraptor extends MowzieModelBase {
    // fields
    MowzieModelRenderer Head;
    MowzieModelRenderer Beak;
    MowzieModelRenderer Crest;
    MowzieModelRenderer Jaw;
    MowzieModelRenderer Neck;
    MowzieModelRenderer UpperBody;
    MowzieModelRenderer LowerBody;
    MowzieModelRenderer Tail1;
    MowzieModelRenderer Tail2;
    MowzieModelRenderer Tail3;
    MowzieModelRenderer Tail4;
    MowzieModelRenderer Thigh1;
    MowzieModelRenderer Thigh2;
    MowzieModelRenderer Calves1;
    MowzieModelRenderer Calves2;
    MowzieModelRenderer Foot1;
    MowzieModelRenderer Foot2;
    MowzieModelRenderer shoulderLeft;
    MowzieModelRenderer shoulderRight;
    MowzieModelRenderer forearmLeft;
    MowzieModelRenderer forearmRight;
    MowzieModelRenderer FeatherArm1;
    MowzieModelRenderer FeatherArm2;
    MowzieModelRenderer TailFeather1;
    MowzieModelRenderer TailFeather2;
    MowzieModelRenderer TailFeather3;
    MowzieModelRenderer TailFeather4;
    MowzieModelRenderer TailFeather5;
    MowzieModelRenderer TailFeather6;
    MowzieModelRenderer TailFeather7;
    MowzieModelRenderer Ankle1;
    MowzieModelRenderer Ankle2;
    MowzieModelRenderer Finger1;
    MowzieModelRenderer Finger2;
    MowzieModelRenderer Finger3;
    MowzieModelRenderer Finger4;

    public ModelOviraptor() {
        textureWidth = 128;
        textureHeight = 128;

        Head = new MowzieModelRenderer(this, 0, 33);
        Head.addBox(0F, 0F, 0F, 5, 5, 7);
        Head.setRotationPoint(-2.5F, -3F, -9F);
        Head.setTextureSize(textureWidth, textureHeight);
        Head.mirror = true;
        setRotation(Head, 0F, 0F, 0F);
        Beak = new MowzieModelRenderer(this, 0, 19);
        Beak.addBox(0F, 0F, 0F, 5, 1, 1);
        Beak.setRotationPoint(-2.5F, 2F, -9F);
        Beak.setTextureSize(textureWidth, textureHeight);
        Beak.mirror = true;
        setRotation(Beak, 0.4363323F, 0F, 0F);
        Crest = new MowzieModelRenderer(this, 0, 7);
        Crest.addBox(0F, 0F, 0F, 2, 5, 6);
        Crest.setRotationPoint(-1F, -4.5F, -10.5F);
        Crest.setTextureSize(textureWidth, textureHeight);
        Crest.mirror = true;
        setRotation(Crest, 0.4363323F, 0F, 0F);
        Jaw = new MowzieModelRenderer(this, 0, 0);
        Jaw.addBox(0F, 0F, 0F, 4, 1, 5);
        Jaw.setRotationPoint(-2F, 2F, -8F);
        Jaw.setTextureSize(textureWidth, textureHeight);
        Jaw.mirror = true;
        setRotation(Jaw, 0F, 0F, 0F);
        Neck = new MowzieModelRenderer(this, 30, 0);
        Neck.addBox(0F, 0F, 0F, 2, 10, 3);
        Neck.setRotationPoint(-1F, -1F, -4.9F);
        Neck.setTextureSize(textureWidth, textureHeight);
        Neck.mirror = true;
        setRotation(Neck, 0.3717861F, 0F, 0F);
        UpperBody = new MowzieModelRenderer(this, 40, 0);
        UpperBody.addBox(0F, 0F, -1F, 6, 6, 6);
        UpperBody.setRotationPoint(-3F, 5F, 0F);
        UpperBody.setTextureSize(textureWidth, textureHeight);
        UpperBody.mirror = true;
        setRotation(UpperBody, -0.0872665F, 0F, 0F);
        LowerBody = new MowzieModelRenderer(this, 34, 12);
        LowerBody.addBox(0F, 0F, -1F, 8, 7, 7);
        LowerBody.setRotationPoint(-4F, 5.4F, 5F);
        LowerBody.setTextureSize(textureWidth, textureHeight);
        LowerBody.mirror = true;
        setRotation(LowerBody, 0F, 0F, 0F);
        Tail1 = new MowzieModelRenderer(this, 40, 26);
        Tail1.addBox(-0.5F, 0F, -1F, 5, 5, 7);
        Tail1.setRotationPoint(-2F, 5.9F, 11F);
        Tail1.setTextureSize(textureWidth, textureHeight);
        Tail1.mirror = true;
        setRotation(Tail1, -0.0129092F, 0F, 0F);
        Tail2 = new MowzieModelRenderer(this, 66, 26);
        Tail2.addBox(-2F, 0F, 0F, 4, 4, 6);
        Tail2.setRotationPoint(0F, 6.4F, 16F);
        Tail2.setTextureSize(textureWidth, textureHeight);
        Tail2.mirror = true;
        setRotation(Tail2, -0.0872665F, 0F, 0F);
        Tail3 = new MowzieModelRenderer(this, 66, 38);
        Tail3.addBox(-1.5F, 0F, 0F, 3, 3, 6);
        Tail3.setRotationPoint(0F, 7.2F, 20F);
        Tail3.setTextureSize(textureWidth, textureHeight);
        Tail3.mirror = true;
        setRotation(Tail3, -0.0872665F, 0F, 0F);
        Tail4 = new MowzieModelRenderer(this, 20, 17);
        Tail4.addBox(0F, 0F, -1F, 2, 2, 10);
        Tail4.setRotationPoint(-1F, 8F, 24F);
        Tail4.setTextureSize(textureWidth, textureHeight);
        Tail4.mirror = true;
        setRotation(Tail4, -0.0698132F, 0F, 0F);
        Thigh1 = new MowzieModelRenderer(this, 2, 48);
        Thigh1.addBox(0F, 0F, -1F, 2, 7, 5);
        Thigh1.setRotationPoint(4F, 7.4F, 7F);
        Thigh1.setTextureSize(textureWidth, textureHeight);
        Thigh1.mirror = true;
        setRotation(Thigh1, -0.3839724F, 0F, 0F);
        Thigh2 = new MowzieModelRenderer(this, 2, 48);
        Thigh2.addBox(-2F, 0F, -1F, 2, 7, 5);
        Thigh2.setRotationPoint(-4F, 7.4F, 7F);
        Thigh2.setTextureSize(textureWidth, textureHeight);
        Thigh2.mirror = true;
        setRotation(Thigh2, -0.3839724F, 0F, 0F);
        Calves1 = new MowzieModelRenderer(this, 18, 29);
        Calves1.addBox(0F, 0F, -1F, 2, 9, 2);
        Calves1.setRotationPoint(4F, 12.4F, 5F);
        Calves1.setTextureSize(textureWidth, textureHeight);
        Calves1.mirror = true;
        setRotation(Calves1, 0.6108652F, 0F, 0F);
        Calves2 = new MowzieModelRenderer(this, 18, 29);
        Calves2.addBox(-2F, 0F, -1F, 2, 9, 2);
        Calves2.setRotationPoint(-4F, 12.4F, 5F);
        Calves2.setTextureSize(textureWidth, textureHeight);
        Calves2.mirror = true;
        setRotation(Calves2, 0.6108652F, 0F, 0F);
        Foot1 = new MowzieModelRenderer(this, 25, 38);
        Foot1.addBox(0F, 0F, 0F, 3, 2, 5);
        Foot1.setRotationPoint(3.5F, 22F, 3F);
        Foot1.setTextureSize(textureWidth, textureHeight);
        Foot1.mirror = true;
        setRotation(Foot1, 0F, 0F, 0F);
        Foot2 = new MowzieModelRenderer(this, 25, 38);
        Foot2.addBox(0F, 0F, 0F, 3, 2, 5);
        Foot2.setRotationPoint(-6.5F, 22F, 3F);
        Foot2.setTextureSize(textureWidth, textureHeight);
        Foot2.mirror = true;
        setRotation(Foot2, 0F, 0F, 0F);
        shoulderLeft = new MowzieModelRenderer(this, 22, 0);
        shoulderLeft.addBox(0F, 0F, 1F, 2, 4, 2);
        shoulderLeft.setRotationPoint(2F, 8.4F, -2F);
        shoulderLeft.setTextureSize(textureWidth, textureHeight);
        shoulderLeft.mirror = true;
        setRotation(shoulderLeft, -0.2617994F, 0F, -0.1745329F);
        shoulderRight = new MowzieModelRenderer(this, 22, 0);
        shoulderRight.addBox(0F, 0F, 1F, 2, 4, 2);
        shoulderRight.setRotationPoint(-4F, 8.4F, -2F);
        shoulderRight.setTextureSize(textureWidth, textureHeight);
        shoulderRight.mirror = true;
        setRotation(shoulderRight, -0.2617994F, 0F, 0.1745329F);
        forearmLeft = new MowzieModelRenderer(this, 22, 6);
        forearmLeft.addBox(-2F, 0.2F, -1F, 2, 5, 2);
        forearmLeft.setRotationPoint(5F, 12.2F, -0.8F);
        forearmLeft.setTextureSize(textureWidth, textureHeight);
        forearmLeft.mirror = true;
        setRotation(forearmLeft, -0.7853982F, 0.2617994F, 0F);
        forearmRight = new MowzieModelRenderer(this, 22, 6);
        forearmRight.addBox(0F, 0.2F, -1F, 2, 5, 2);
        forearmRight.setRotationPoint(-5F, 12.2F, -0.8F);
        forearmRight.setTextureSize(textureWidth, textureHeight);
        forearmRight.mirror = true;
        setRotation(forearmRight, -0.7853982F, -0.2617994F, 0F);
        FeatherArm1 = new MowzieModelRenderer(this, 18, 17);
        FeatherArm1.addBox(0F, 0F, -1F, 1, 5, 5);
        FeatherArm1.setRotationPoint(3.5F, 13F, 0.3F);
        FeatherArm1.setTextureSize(textureWidth, textureHeight);
        FeatherArm1.mirror = true;
        setRotation(FeatherArm1, -0.7853982F, 0.0872665F, 0F);
        FeatherArm2 = new MowzieModelRenderer(this, 18, 17);
        FeatherArm2.addBox(0F, 0F, -1F, 1, 5, 5);
        FeatherArm2.setRotationPoint(-4.5F, 13F, 0.3F);
        FeatherArm2.setTextureSize(textureWidth, textureHeight);
        FeatherArm2.mirror = true;
        setRotation(FeatherArm2, -0.7853982F, -0.0872665F, 0F);
        TailFeather1 = new MowzieModelRenderer(this, 36, 38);
        TailFeather1.addBox(0F, 0F, 0F, 4, 1, 10);
        TailFeather1.setRotationPoint(-2F, 8.5F, 28F);
        TailFeather1.setTextureSize(textureWidth, textureHeight);
        TailFeather1.mirror = true;
        setRotation(TailFeather1, -0.2443461F, 0F, 0F);
        TailFeather2 = new MowzieModelRenderer(this, 36, 38);
        TailFeather2.addBox(0F, 0F, 0.8F, 4, 1, 10);
        TailFeather2.setRotationPoint(-2F, 8.5F, 29F);
        TailFeather2.setTextureSize(textureWidth, textureHeight);
        TailFeather2.mirror = true;
        setRotation(TailFeather2, 0.0174533F, 0.4363323F, 0F);
        TailFeather3 = new MowzieModelRenderer(this, 36, 38);
        TailFeather3.addBox(0F, 0F, -1F, 4, 1, 10);
        TailFeather3.setRotationPoint(-2.5F, 8.5F, 29F);
        TailFeather3.setTextureSize(textureWidth, textureHeight);
        TailFeather3.mirror = true;
        setRotation(TailFeather3, 0.0174533F, -0.4363323F, 0F);
        TailFeather4 = new MowzieModelRenderer(this, 36, 38);
        TailFeather4.addBox(0F, 0F, 0F, 4, 1, 10);
        TailFeather4.setRotationPoint(-2F, 8.5F, 28F);
        TailFeather4.setTextureSize(textureWidth, textureHeight);
        TailFeather4.mirror = true;
        setRotation(TailFeather4, 0.1047198F, 0F, 0F);
        TailFeather5 = new MowzieModelRenderer(this, 36, 38);
        TailFeather5.addBox(0F, 0F, 0F, 4, 1, 10);
        TailFeather5.setRotationPoint(-2F, 8.5F, 28F);
        TailFeather5.setTextureSize(textureWidth, textureHeight);
        TailFeather5.mirror = true;
        setRotation(TailFeather5, -0.0698132F, 0F, 0F);
        TailFeather6 = new MowzieModelRenderer(this, 36, 38);
        TailFeather6.addBox(0F, 0F, 0.8F, 4, 1, 10);
        TailFeather6.setRotationPoint(-2F, 8.5F, 29F);
        TailFeather6.setTextureSize(textureWidth, textureHeight);
        TailFeather6.mirror = true;
        setRotation(TailFeather6, -0.1570796F, 0.4363323F, 0F);
        TailFeather7 = new MowzieModelRenderer(this, 36, 38);
        TailFeather7.addBox(0F, 0F, -1F, 4, 1, 10);
        TailFeather7.setRotationPoint(-2.5F, 9F, 29F);
        TailFeather7.setTextureSize(textureWidth, textureHeight);
        TailFeather7.mirror = true;
        setRotation(TailFeather7, -0.1570796F, -0.4363323F, 0.0174533F);
        Ankle1 = new MowzieModelRenderer(this, 32, 57);
        Ankle1.addBox(0F, 0F, 0F, 2, 2, 5);
        Ankle1.setRotationPoint(4F, 22F, 5.5F);
        Ankle1.setTextureSize(textureWidth, textureHeight);
        Ankle1.mirror = true;
        setRotation(Ankle1, 0.8726646F, 0F, 0F);
        Ankle2 = new MowzieModelRenderer(this, 32, 57);
        Ankle2.addBox(0F, 0F, 0F, 2, 2, 5);
        Ankle2.setRotationPoint(-6F, 22F, 5.5F);
        Ankle2.setTextureSize(textureWidth, textureHeight);
        Ankle2.mirror = true;
        setRotation(Ankle2, 0.8726646F, 0F, 0F);
        Finger1 = new MowzieModelRenderer(this, 5, 22);
        Finger1.addBox(0F, 0F, 0F, 1, 2, 1);
        Finger1.setRotationPoint(-4F, 16.46667F, -4F);
        Finger1.setTextureSize(textureWidth, textureHeight);
        Finger1.mirror = true;
        setRotation(Finger1, 0F, 0.5235988F, -0.8726646F);
        Finger2 = new MowzieModelRenderer(this, 5, 22);
        Finger2.addBox(0F, 0F, 0F, 1, 2, 1);
        Finger2.setRotationPoint(-3.5F, 15.5F, -4F);
        Finger2.setTextureSize(textureWidth, textureHeight);
        Finger2.mirror = true;
        setRotation(Finger2, 0F, 0.5235988F, -0.8726646F);
        Finger3 = new MowzieModelRenderer(this, 5, 22);
        Finger3.addBox(-1F, 0F, 0F, 1, 2, 1);
        Finger3.setRotationPoint(3.5F, 15.5F, -4F);
        Finger3.setTextureSize(textureWidth, textureHeight);
        Finger3.mirror = true;
        setRotation(Finger3, 0F, -0.5235988F, 0.8726646F);
        Finger4 = new MowzieModelRenderer(this, 5, 22);
        Finger4.addBox(-1F, 0F, 0F, 1, 2, 1);
        Finger4.setRotationPoint(4F, 16.5F, -4F);
        Finger4.setTextureSize(textureWidth, textureHeight);
        Finger4.mirror = true;
        setRotation(Finger4, 0F, -0.5235988F, 0.8726646F);

        addChildTo(Beak, Head);
        addChildTo(Crest, Head);
        addChildTo(Jaw, Head);
        addChildTo(Head, Neck);
        addChildTo(Neck, UpperBody);

        addChildTo(FeatherArm1, forearmLeft);
        addChildTo(Finger3, forearmLeft);
        addChildTo(Finger4, forearmLeft);
        addChildTo(forearmLeft, shoulderLeft);
        addChildTo(FeatherArm2, forearmRight);
        addChildTo(Finger1, forearmRight);
        addChildTo(Finger2, forearmRight);
        addChildTo(forearmRight, shoulderRight);
        addChildTo(shoulderRight, LowerBody);
        addChildTo(shoulderLeft, LowerBody);

        addChildTo(UpperBody, LowerBody);

        addChildTo(TailFeather1, Tail4);
        addChildTo(TailFeather2, Tail4);
        addChildTo(TailFeather3, Tail4);
        addChildTo(TailFeather4, Tail4);
        addChildTo(TailFeather5, Tail4);
        addChildTo(TailFeather6, Tail4);
        addChildTo(TailFeather7, Tail4);
        addChildTo(Tail4, Tail3);
        addChildTo(Tail3, Tail2);
        addChildTo(Tail2, Tail1);
        addChildTo(Tail1, LowerBody);

        addChildTo(Foot1, Ankle1);
        addChildTo(Ankle1, Calves1);
        addChildTo(Calves1, Thigh1);
        addChildTo(Foot2, Ankle2);
        addChildTo(Ankle2, Calves2);
        addChildTo(Calves2, Thigh2);

        // Corrections
        Crest.rotationPointZ -= 3;
        Crest.rotationPointY -= 3;
        Head.rotationPointZ -= 6;
        Head.rotationPointY -= 6;
        Neck.rotationPointY -= 13;
        Neck.rotationPointZ -= 11;
        UpperBody.rotationPointY -= 1;
        UpperBody.rotationPointZ -= 10;
        forearmLeft.rotationPointX -= 0.6;
        forearmRight.rotationPointX += 0.6;
        Finger1.rotateAngleZ += 0.5;
        Finger2.rotateAngleZ += 0.5;
        Finger1.rotationPointY += 0.5;
        Finger2.rotationPointY += 0.5;
        Finger3.rotateAngleZ -= 0.5;
        Finger4.rotateAngleZ -= 0.5;
        Finger3.rotationPointY += 0.5;
        Finger4.rotationPointY += 0.5;

        this.updateDefaultPose();
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, (EntityOviraptor) entity);
        // Head.render(f5);
        // Crest.render(f5);
        // Beak.render(f5);
        // Jaw.render(f5);
        // Neck.render(f5);
        // UpperBody.render(f5);
        LowerBody.render(f5);
        // Tail1.render(f5);
        // Tail2.render(f5);
        // Tail3.render(f5);
        // Tail4.render(f5);
        Thigh1.render(f5);
        Thigh2.render(f5);
        // Calves1.render(f5);
        // Calves2.render(f5);
        // Foot1.render(f5);
        // Foot2.render(f5);
        // shoulderLeft.render(f5);
        // shoulderRight.render(f5);
        // forearmLeft.render(f5);
        // forearmRight.render(f5);
        // FeatherArm1.render(f5);
        // FeatherArm2.render(f5);
        // TailFeather1.render(f5);
        // TailFeather2.render(f5);
        // TailFeather3.render(f5);
        // TailFeather4.render(f5);
        // TailFeather5.render(f5);
        // TailFeather6.render(f5);
        // TailFeather7.render(f5);
        // Ankle1.render(f5);
        // Ankle2.render(f5);
        // Finger1.render(f5);
        // Finger2.render(f5);
        // Finger3.render(f5);
        // Finger4.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, EntityOviraptor ovi) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, null);

        this.resetToDefaultPose();
        f = ovi.frame;
        f1 = 0.5F;
        float globalSpeed = 0.5F, globalDegree = 1;
        this.bob(LowerBody, 1F * globalSpeed, 1F, false, f, f1);
        this.bob(Thigh1, 1F * globalSpeed, 1F, false, f, f1);
        this.bob(Thigh2, 1F * globalSpeed, 1F, false, f, f1);
        this.walk(Thigh1, 0.5F * globalSpeed, 0.8F * globalDegree, false, 0, 0.4F, f, f1);
        this.walk(Thigh2, 0.5F * globalSpeed, 0.8F * globalDegree, true, 0, 0.4F, f, f1);
        this.walk(Calves1, 0.5F * globalSpeed, 0.5F * globalDegree, true, 1F, 0F, f, f1);
        this.walk(Calves2, 0.5F * globalSpeed, 0.5F * globalDegree, false, 1F, 0F, f, f1);
        this.walk(Ankle1, 0.5F * globalSpeed, 0.5F * globalDegree, false, 0F, 0F, f, f1);
        this.walk(Ankle2, 0.5F * globalSpeed, 0.5F * globalDegree, true, 0F, 0F, f, f1);
        this.walk(Foot1, 0.5F * globalSpeed, 0.5F * globalDegree, true, 0F, 0F, f, f1);
        this.walk(Foot2, 0.5F * globalSpeed, 0.5F * globalDegree, false, 0F, 0F, f, f1);

        this.walk(Neck, 1F * globalSpeed, 0.25F * globalDegree, false, 1F, 0.4F, f, f1);
    }
}