// Date: 13.06.2014 13:05:07
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package net.ilexiconn.jurassicraft.client.model.entity;

import net.ilexiconn.jurassicraft.client.model.base.MowzieModelBase;
import net.ilexiconn.jurassicraft.client.model.base.MowzieModelRenderer;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelLeaellynasaura extends MowzieModelBase {
    // fields
    MowzieModelRenderer body;
    MowzieModelRenderer neck;
    MowzieModelRenderer head;
    MowzieModelRenderer bottombeak;
    MowzieModelRenderer mouthtop;
    MowzieModelRenderer upperleg;
    MowzieModelRenderer upperleg1;
    MowzieModelRenderer midleg;
    MowzieModelRenderer midleg1;
    MowzieModelRenderer lowerleg;
    MowzieModelRenderer lowerleg1;
    MowzieModelRenderer feet;
    MowzieModelRenderer feet1;
    MowzieModelRenderer tail;
    MowzieModelRenderer shoulder1;
    MowzieModelRenderer arm;
    MowzieModelRenderer shoulder;
    MowzieModelRenderer arm1;
    MowzieModelRenderer body1;
    MowzieModelRenderer tailback;

    public ModelLeaellynasaura() {
        textureWidth = 128;
        textureHeight = 64;

        body = new MowzieModelRenderer(this, 0, 32);
        body.addBox(-1.5F, 0F, 0F, 3, 3, 5);
        body.setRotationPoint(0F, 14F, -6F);
        body.setTextureSize(128, 64);
        body.mirror = true;
        setRotation(body, 0F, 0F, 0F);
        neck = new MowzieModelRenderer(this, 20, 0);
        neck.addBox(-1F, 0F, 0F, 2, 2, 6);
        neck.setRotationPoint(0F, 10F, -7F);
        neck.setTextureSize(128, 64);
        neck.mirror = true;
        setRotation(neck, -1F, 0F, 0F);
        head = new MowzieModelRenderer(this, 0, 0);
        head.addBox(-1F, 0F, 0F, 2, 2, 3);
        head.setRotationPoint(0F, 10F, -10F);
        head.setTextureSize(128, 64);
        head.mirror = true;
        setRotation(head, 0F, 0F, 0F);
        bottombeak = new MowzieModelRenderer(this, 0, 16);
        bottombeak.addBox(-1F, 0F, 0F, 2, 1, 1);
        bottombeak.setRotationPoint(0F, 11F, -11F);
        bottombeak.setTextureSize(128, 64);
        bottombeak.mirror = true;
        setRotation(bottombeak, 0F, 0F, 0F);
        mouthtop = new MowzieModelRenderer(this, 0, 16);
        mouthtop.addBox(-1F, 0F, 0F, 2, 1, 1);
        mouthtop.setRotationPoint(0F, 10F, -11F);
        mouthtop.setTextureSize(128, 64);
        mouthtop.mirror = true;
        setRotation(mouthtop, 0F, 0F, 0F);
        upperleg = new MowzieModelRenderer(this, 35, 35);
        upperleg.addBox(-3F, 0F, 0F, 2, 5, 3);
        upperleg.setRotationPoint(0F, 14F, 2F);
        upperleg.setTextureSize(128, 64);
        upperleg.mirror = true;
        setRotation(upperleg, -0.5948606F, 0F, 0F);
        upperleg1 = new MowzieModelRenderer(this, 35, 35);
        upperleg1.addBox(0F, 0F, 0F, 2, 5, 3);
        upperleg1.setRotationPoint(1F, 14F, 2F);
        upperleg1.setTextureSize(128, 64);
        upperleg1.mirror = true;
        setRotation(upperleg1, -0.5948578F, 0F, 0F);
        midleg = new MowzieModelRenderer(this, 0, 20);
        midleg.addBox(-0.5F, 0F, 0F, 1, 4, 1);
        midleg.setRotationPoint(-2F, 19F, 0F);
        midleg.setTextureSize(128, 64);
        midleg.mirror = true;
        setRotation(midleg, 1F, 0F, 0F);
        midleg1 = new MowzieModelRenderer(this, 0, 20);
        midleg1.addBox(-0.5F, 0F, 0F, 1, 4, 1);
        midleg1.setRotationPoint(2F, 19F, 0F);
        midleg1.setTextureSize(128, 64);
        midleg1.mirror = true;
        setRotation(midleg1, 1F, 0F, 0F);
        lowerleg = new MowzieModelRenderer(this, 0, 25);
        lowerleg.addBox(-0.5F, 0F, 0F, 1, 4, 1);
        lowerleg.setRotationPoint(-2F, 20F, 3F);
        lowerleg.setTextureSize(128, 64);
        lowerleg.mirror = true;
        setRotation(lowerleg, -0.4461411F, 0F, 0F);
        lowerleg1 = new MowzieModelRenderer(this, 0, 25);
        lowerleg1.addBox(-0.5F, 0F, 0F, 1, 4, 1);
        lowerleg1.setRotationPoint(2F, 20F, 3F);
        lowerleg1.setTextureSize(128, 64);
        lowerleg1.mirror = true;
        setRotation(lowerleg1, -0.4461433F, 0F, 0F);
        feet = new MowzieModelRenderer(this, 25, 25);
        feet.addBox(-1F, 0F, 0F, 2, 1, 3);
        feet.setRotationPoint(2F, 23F, 0F);
        feet.setTextureSize(128, 64);
        feet.mirror = true;
        setRotation(feet, 0F, 0F, 0F);
        feet1 = new MowzieModelRenderer(this, 25, 25);
        feet1.addBox(-1F, 0F, 0F, 2, 1, 3);
        feet1.setRotationPoint(-2F, 23F, 0F);
        feet1.setTextureSize(128, 64);
        feet1.mirror = true;
        setRotation(feet1, 0F, 0F, 0F);
        tail = new MowzieModelRenderer(this, 48, 0);
        tail.addBox(-0.5F, 0F, 0F, 1, 1, 9);
        tail.setRotationPoint(0F, 14.8F, 6F);
        tail.setTextureSize(128, 64);
        tail.mirror = true;
        setRotation(tail, -0.1115358F, 0F, 0F);
        shoulder1 = new MowzieModelRenderer(this, 50, 0);
        shoulder1.addBox(0F, 0F, 0F, 1, 3, 1);
        shoulder1.setRotationPoint(1.5F, 15F, -5.5F);
        shoulder1.setTextureSize(128, 64);
        shoulder1.mirror = true;
        setRotation(shoulder1, 0.4089647F, 0F, 0F);
        arm = new MowzieModelRenderer(this, 50, 22);
        arm.addBox(-0.5F, 0F, 0F, 1, 3, 1);
        arm.setRotationPoint(2F, 16.5F, -4F);
        arm.setTextureSize(128, 64);
        arm.mirror = true;
        setRotation(arm, -1F, 0F, 0F);
        shoulder = new MowzieModelRenderer(this, 50, 0);
        shoulder.addBox(-1F, 0F, 0F, 1, 3, 1);
        shoulder.setRotationPoint(-1.5F, 15F, -5.5F);
        shoulder.setTextureSize(128, 64);
        shoulder.mirror = true;
        setRotation(shoulder, 0.4089656F, 0F, 0F);
        arm1 = new MowzieModelRenderer(this, 50, 22);
        arm1.addBox(-0.5F, 0F, 0F, 1, 3, 1);
        arm1.setRotationPoint(-2F, 16.5F, -4F);
        arm1.setTextureSize(128, 64);
        arm1.mirror = true;
        setRotation(arm1, -1F, 0F, 0F);
        body1 = new MowzieModelRenderer(this, 0, 50);
        body1.addBox(-1.5F, 0F, 0F, 3, 4, 5);
        body1.setRotationPoint(0F, 14F, -1F);
        body1.setTextureSize(128, 64);
        body1.mirror = true;
        setRotation(body1, 0F, 0F, 0F);
        tailback = new MowzieModelRenderer(this, 50, 50);
        tailback.addBox(-1F, 0F, 0F, 2, 2, 3);
        tailback.setRotationPoint(0F, 14F, 4F);
        tailback.setTextureSize(128, 64);
        tailback.mirror = true;
        setRotation(tailback, -0.1115358F, 0F, 0F);

        addChildTo(feet1, lowerleg);
        addChildTo(lowerleg, midleg);
        addChildTo(midleg, upperleg);

        addChildTo(feet, lowerleg1);
        addChildTo(lowerleg1, midleg1);
        addChildTo(midleg1, upperleg1);

        body.updateDefaultPose();
        neck.updateDefaultPose();
        head.updateDefaultPose();
        bottombeak.updateDefaultPose();
        mouthtop.updateDefaultPose();
        upperleg.updateDefaultPose();
        upperleg1.updateDefaultPose();
        midleg.updateDefaultPose();
        midleg1.updateDefaultPose();
        lowerleg.updateDefaultPose();
        lowerleg1.updateDefaultPose();
        feet.updateDefaultPose();
        feet1.updateDefaultPose();
        tail.updateDefaultPose();
        shoulder1.updateDefaultPose();
        arm1.updateDefaultPose();
        shoulder.updateDefaultPose();
        arm.updateDefaultPose();
        body1.updateDefaultPose();
        tailback.updateDefaultPose();
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5);
        body.render(f5);
        neck.render(f5);
        head.render(f5);
        bottombeak.render(f5);
        mouthtop.render(f5);
        upperleg.render(f5);
        upperleg1.render(f5);
        // midleg.render(f5);
        // midleg1.render(f5);
        // lowerleg.render(f5);
        // lowerleg1.render(f5);
        // feet.render(f5);
        // feet1.render(f5);
        tail.render(f5);
        shoulder1.render(f5);
        arm1.render(f5);
        shoulder.render(f5);
        arm.render(f5);
        body1.render(f5);
        tailback.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void resetPose() {
        body.resetToDefaultPose();
        neck.resetToDefaultPose();
        head.resetToDefaultPose();
        bottombeak.resetToDefaultPose();
        mouthtop.resetToDefaultPose();
        upperleg.resetToDefaultPose();
        upperleg1.resetToDefaultPose();
        midleg.resetToDefaultPose();
        midleg1.resetToDefaultPose();
        lowerleg.resetToDefaultPose();
        lowerleg1.resetToDefaultPose();
        feet.resetToDefaultPose();
        feet1.resetToDefaultPose();
        tail.resetToDefaultPose();
        shoulder1.resetToDefaultPose();
        arm1.resetToDefaultPose();
        shoulder.resetToDefaultPose();
        arm.resetToDefaultPose();
        body1.resetToDefaultPose();
        tailback.resetToDefaultPose();
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
        resetPose();
        walk(upperleg, 0.7F, 0.5F, false, 0F, 0, f, f1);
        walk(upperleg1, 0.7F, 0.5F, true, 0F, 0, f, f1);
    }

}
